# set wmname
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

# do some autostarts
tabbed -c vimb -e
thunderbird &
udiskie &
pulseaudio --start &
statnot $HOME/.config/statnot/config.py &
pomo.sh notify &

# set keyboard layout to Swiss German
#setxkbmap ch -option apple:badmap

# Run dwm
exec dwm
